### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [TigerBeanst/TigerInTheWall#20]
请问是否可以将应用发布到 F-Droid？

**Comment by TigerBeanst** [comment]
目前暂无计划，因为应用会包含 Firebase 作为统计，导致无法 FOSS

**Comment by linsui** [comment]
在 F-Droid 构建时去掉相关代码不会很难。如果你同意发布我可以编写构建元数据并提交。

**Comment by TigerBeanst** [comment]
> 在 F-Droid 构建时去掉相关代码不会很难。如果你同意发布我可以编写构建元数据并提交。

不是的，主要是我想用 Firebase 大概了解一下用户量和版本更新情况……

**Comment by linsui** [comment]
如果愿意迁移到 Sentry 或 ACRA 之类 FOSS 的解决方案也可以，但工作量会比较大，我不是 Android 开发者所以没有办法提交 PR 添加一个 flavor 之类的。 :shrug:

**Comment by TigerBeanst** [comment]
> 如果愿意迁移到 Sentry 或 ACRA 之类 FOSS 的解决方案也可以，但工作量会比较大，我不是 Android 开发者所以没有办法提交 PR 添加一个 flavor 之类的。 🤷

好德，我看一下~

**Comment by TigerBeanst** [comment]
https://gitlab.com/fdroid/fdroiddata/-/blob/9fcf09cea722cd8d2701f63ae09d945d4aec62b8/metadata/com.github.shadowsocks.yml
在知悉 F-Droid 在作者拒绝，声称与源代码相同的情况下，通过删除 Firebase 等代码强行上架后，我决定不再考虑 F-Droid。
